package controllers;

public enum Commands {
	ADD_ORDER, UPDATE_ORDER, SEARCH_ORDER, BACK_RESGISTER_ORDER, SAVE_ORDER, SELECT_SEARCH, CANCEL_SELECT_SEARCH,
	INTRODUCE_VALUE_SEARCH, SEARCH_ORDER_BY_ID, UPDATE_ORDER_IN_DB
}
